function repairBrokenUnits(text){return String(text||'').replace(/(\d+(?:[.,]\d+)?)\s*\n\s*(개월|년|주|일|시간|분|명|만원|원|%)/g,'$1$2');}
function cleanListPrefix(value){return String(value||'').replace(/\r/g,'').trim().replace(/^\s*(?:(?:[-–—*•▪◦])\s*)+/,'').replace(/^\s*\d{1,2}\s*[.)]\s+/,'').trim();}
function isKnownSectionLine(value){const c=cleanListPrefix(value).replace(/^\s*[\[【(]\s*/,'').replace(/\s*[\]】)]\s*$/,'').replace(/\s+/g,'').replace(/[:：]+$/,''); return /^(담당업무|주요업무|업무내용|담당직무|직무내용|주요역할|지원자격|자격요건|필수요건|필요요건|지원요건|고용조건|고용형태|근무조건|근무기간|근무시간|채용형태|계약형태|우대사항|우대자격|우대요건|우대조건|선호사항|선호요건|포지션상세|포지션소개|혜택및복지|복리후생|혜택|채용전형|전형절차|채용절차|채용프로세스|근무지|근무지역|접수방법|기타사항|회사소개|채용정보|모집기간|경력)$/i.test(c);}
function bracketDelta(value){const s=String(value||''); const open=(s.match(/[([{]/g)||[]).length; const close=(s.match(/[)\]}]/g)||[]).length; return open-close;}
function joinListFragment(left,right){const a=String(left||'').trim(); const b=String(right||'').trim(); if(!a)return b; if(!b)return a; const noSpace=/[([{\/]$/.test(a)||/^[)\]}\/,.:;]/.test(b); return a+(noSpace?'':' ')+b;}
function splitItems(text){let raw=repairBrokenUnits(text).replace(/\r/g,''); raw=raw.replace(/([^\n])\s+([•▪◦])\s+(?=\S)/g,'$1\n$2 '); const lines=raw.split(/\n/).map(v=>v.trim()).filter(Boolean); const items=[]; let current=''; let depth=0; const flush=()=>{const v=cleanListPrefix(current); if(v)items.push(v); current=''; depth=0;}; for(const line of lines){const marked=/^\s*(?:(?:[-–—*•▪◦])+|\d{1,2}\s*[.)])\s*/.test(line); const cleaned=cleanListPrefix(line); if(!cleaned)continue; if(isKnownSectionLine(line)){flush(); items.push(cleaned); continue;} if(marked){flush(); current=cleaned; depth=Math.max(0,bracketDelta(cleaned)); continue;} if(!current){current=cleaned; depth=Math.max(0,bracketDelta(cleaned)); continue;} const punctuationOnly=/^[()[\]{},/·:;]+$/.test(cleaned); const shortAcronym=/^[A-Za-z][A-Za-z0-9+.#/-]{0,9}$/.test(current.trim()); if(depth>0||punctuationOnly||shortAcronym||/^[)\]}\/,.:;]/.test(cleaned)){current=joinListFragment(current,cleaned); depth=Math.max(0,depth+bracketDelta(cleaned));}else{flush(); current=cleaned; depth=Math.max(0,bracketDelta(cleaned));}} flush(); return items;}
const raw=`우대사항\n• • 유관 자격증 소지자 우대\n(\n미국\n/\n영국\n/\n호주 회계사\n,\n보험계리사\n, CISA, CIA, CISM, SQLD 등)\n• IT\n관련한 경험 및 금융회사 경험 우대\n고용조건\n• 인턴 6\n개월`;
const got=splitItems(raw);
const expected=["우대사항","유관 자격증 소지자 우대 (미국/영국/호주 회계사, 보험계리사, CISA, CIA, CISM, SQLD 등)","IT 관련한 경험 및 금융회사 경험 우대","고용조건","인턴 6개월"];
if(JSON.stringify(got)!==JSON.stringify(expected)){console.error({got,expected}); process.exit(1);} console.log('PASS: JSON 목록 변환에서 조각난 괄호·슬래시·IT 문장을 복원합니다.');
